apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
          args:
            - redpanda
            - start
            - --smp
            - "1"
            - --memory
            - "512M"
            - --reserve-memory
            - "0M"
            - --overprovisioned
            - --node-id
            - "0"
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://kafka:9092
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: journal
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
